# **Relatório de Análise IV**

Neste Relatório, o nosso obejtivo constistirá em determinar a quantidade de imóveis que obdecem as seguintes condições:

* Imóveis classificados como 'Apartamento'
* Imóveis classificados como 'Casa','Casa de Condominio' e 'Casa de Vila'
* imóveis com área entre 60 e 100 metros quadrados, incluindo os limmites.
* Imóveis com pelo menos 4 quartos e aluguel de até R$2.000,00.

# **Determinando a Frequência de cada Tipo de Imóvel**

In [1]:
# importa o pandas com o apelido pd
import pandas as pd

# importa o CSV com os dados de imóveis residenciais
imoveis = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Analise de Dados/Análise de Dados de imóveis/imoveis-residenciais (1).csv', sep=';')

# Exibe as cincos primeiras linhas do dataFrame
imoveis.head()

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
3,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
4,Apartamento,Vista Alegre,3,1,0,70,1200.0,NaN,NaN

In [2]:
# Seleciona somente os imóveis do tipo casa, casa de condomínio e casa de vila
filtro = imoveis['Tipo'] == 'Apartamento'

# Obtém o número de imóveis dos tipos especificados
n1 = imoveis[filtro].shape[0]

# Exibe o tamanho da série
n1

19532

In [4]:
# Seleciona somente os imóveis do tipo casa, casa de condomínio e casa de vila
filtro = imoveis['Tipo'].isin(['Casa', 'Casa de Condomínio', 'Casa de Vila'])

# Obtém o número de imóveis dos tipos especificados
n2 = imoveis[filtro].shape[0]

# Exibe o Tamanho da Série
n2

2212

In [6]:
# seleciona os imóveis com área entre 60  e 100 metros quadrados, incluindo os limites
filtro = (imoveis['Area'] >= 60) & (imoveis['Area'] <= 100)

# Obtém o número de imóveis com as áreas obdecendo as condições
n3 = imoveis[filtro].shape[0]

# Exibe o tamanho da série
n3

8719

In [8]:
# Seleciona os imóveis com pelo menos 4 quartos e com aluguel menor que R$2.000,00
filtro = (imoveis['Quartos'] >= 4) & (imoveis['Valor'] < 2000)

# Obtém o número de imóveis com pelo menos 4 quartos e aluguel inferior a R$2.000,00
n4 = imoveis[filtro].shape[0]

# Exibe o número da série
n4

41

In [9]:
print(f"N° de imóveis classificados como 'Apartamento': {n1}")
print(f"N° de imóveis classificados como 'Casa' ,'Casa de Condomínio' ou 'Casa de Vila': {n2}")
print(f"N° de imóveis com área entre 60 e 100 metros quadrados, incluindo os limites 'Apartamento': {n3}")
print(f"N° de imóveis com pelo menos 4 quartos e aluguel de até R$2.000,00: {n4}")

N° de imóveis classificados como 'Apartamento': 19532
N° de imóveis classificados como 'Casa' ,'Casa de Condomínio' ou 'Casa de Vila': 2212
N° de imóveis com área entre 60 e 100 metros quadrados, incluindo os limites 'Apartamento': 8719
N° de imóveis com pelo menos 4 quartos e aluguel de até R$2.000,00: 41